services:
  # -------------------------
  # PostgreSQL (core transaccional)
  # -------------------------
  postgres:
    image: postgres:16
    container_name: rbnb_postgres
    environment:
      POSTGRES_DB: rbnb
      POSTGRES_USER: rbnb
      POSTGRES_PASSWORD: rbnb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./postgres/initdb:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rbnb -d rbnb"]
      interval: 5s
      timeout: 5s
      retries: 30

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: rbnb_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY: "False"
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy

  # -------------------------
  # MongoDB (standalone, sin sharding)
  # -------------------------
  mongo:
    image: mongo:8
    container_name: rbnb_mongo
    command: ["mongod","--port","27017","--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --port 27017 --eval 'db.runCommand({ ping: 1 }).ok' --quiet | grep 1 >/dev/null"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s

  # -------------------------
  # Init Mongo (one-shot): índices y preparación
  # -------------------------
  mongo_init:
    image: mongo:8
    container_name: rbnb_mongo_init
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./mongo/init/init-mongo.sh:/scripts/init-mongo.sh:ro
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: "27017"
      MONGO_DB: rbnb
    entrypoint: ["bash", "/scripts/init-mongo.sh"]
    restart: "no"

  # -------------------------
  # Generador de datos (one-shot)
  # -------------------------
  generator:
    build:
      context: ./generator
    container_name: rbnb_generator
    environment:
      PGHOST: postgres
      PGPORT: "5432"
      PGDATABASE: rbnb
      PGUSER: rbnb
      PGPASSWORD: rbnb

      # Mongo standalone
      MONGO_URI: mongodb://mongo:27017
      MONGO_DB: rbnb

      GEN_HOSTS: "500"
      GEN_GUESTS: "5000"
      GEN_APTS: "2500"
      GEN_BOOKINGS: "30000"
    depends_on:
      postgres:
        condition: service_healthy
      mongo_init:
        condition: service_completed_successfully
    restart: "no"
    command: ["python", "generate.py"]

volumes:
  pgdata:
  mongodata:
