services:
  mongodb:
    image: mongo:8
    container_name: crypto-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init/init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      MONGO_INITDB_DATABASE: exchange

volumes:
  mongo_data:
