# --- Networking (por defecto suele ir bien, pero lo dejamos explícito) ---
server.default_listen_address=0.0.0.0

# --- Permitir LOAD CSV desde file:/// (directorio import) ---
dbms.security.allow_csv_import_from_file_urls=true

# --- Ruta de import ---
server.directories.import=/data_files
